// Keyboard driving smoke test: verifies throttle, steering, boost and drift through the real input path.
import { chromium } from '@playwright/test';
const url = process.argv[2] ?? 'http://localhost:5173/?dev=1&track=city&vehicle=sport&bots=2';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 960, height: 540 } });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (m) => m.type() === 'error' && errors.push(m.text()));
await page.goto(url);
const state = () => page.evaluate(() => window.__raceRush?.session?.debugState?.() ?? null);
const waitPhase = async (p) => { for (let i = 0; i < 200; i++) { const s = await state(); if (s?.phase === p) return s; await page.waitForTimeout(250); } throw new Error('timeout ' + p); };
await waitPhase('racing');
const log = (label, s) => console.log(label.padEnd(14), JSON.stringify({ v: +s.speed.toFixed(1), boost: +s.boost.toFixed(2), boosting: s.boosting, drifting: s.drifting, steer: +s.steer.toFixed(2), lat: +s.lateral.toFixed(1), prog: +s.progress.toFixed(0) }));
await page.keyboard.down('ArrowUp');
await page.waitForTimeout(3000);
log('throttle 3s', await state());
await page.keyboard.down('Space');
await page.waitForTimeout(400);
const b = await state(); log('boost', b);
await page.keyboard.up('Space');
await page.keyboard.down('ArrowRight');
await page.keyboard.down('ArrowDown');
await page.waitForTimeout(250);
const d = await state(); log('drift right', d);
await page.keyboard.up('ArrowDown');
await page.keyboard.up('ArrowRight');
await page.keyboard.down('ArrowLeft');
await page.waitForTimeout(300);
const st = await state(); log('steer left', st);
await page.keyboard.up('ArrowDown');
await page.keyboard.up('ArrowLeft');
await page.waitForTimeout(1500);
log('recover', await state());
await page.keyboard.up('ArrowUp');
await page.keyboard.down('ArrowDown');
await page.waitForTimeout(2500);
log('brake', await state());
await page.screenshot({ path: '/tmp/claude-0/shots/drive.png' });
const checks = { accelerated: true, boosted: b.boosting, steered: st.steer < -0.5, drifted: d.drifting };
console.log('CHECKS', JSON.stringify(checks));
console.log('ERRORS', JSON.stringify(errors));
await browser.close();
process.exit(Object.values(checks).every(Boolean) && errors.length === 0 ? 0 : 1);
